# Upstream changes from _extends are only recognized when modifications are made to this file in the default branch.
_extends: .github
repository:
  name: aws-ses
  description: This component is responsible for provisioning SES to act as an SMTP gateway
  homepage: https://cloudposse.com/accelerate
  topics: terraform, terraform-component








